version: '3'

services:
  ucenassitant:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ucenassitant-docker
    container_name: ucenassitant
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ASSISTANT_ID: ${OPENAI_ASSISTANT_ID}
      PORT: ${PORT}
    # volumes:
    #   - ./:/var/www/pokedex